In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("messy_customer_sales_data.csv")

In [4]:
print(df)

      Customer_ID               Name  Gender         Age         City  \
0        CUST4371        Paul Wilson      m         52.0     KOLKATA
1        CUST5957       Jason Thomas       M  51.0 years          NaN
2        CUST3754  Brittney Martinez       F        62.0   hyderabad
3        CUST2934      Brenda Pierce  FEMALE        40.0   hyderabad
4        CUST5683    Matthew Carroll      f         41.0     CHENNAI
...           ...                ...     ...         ...          ...
10195   CUST10767       Robert Lewis  female  35.0 years       delhi
10196         NaN        Diane Evans       M        53.0   bangalore
10197    CUST6315    Joshua Martinez      m         25.0   hyderabad
10198    CUST4812       Sarah Miller  FEMALE        55.0          NaN
10199    CUST6588       David Potter  female        34.0   HYDERABAD

      Signup_Date Last_Purchase_Date  Purchase_Amount  Feedback_Score  \
0      2025-06-26         2025-05-17          26944.0             1.0
1      2021-02-17         2025-07-22          44152.0             2.0
2      2023-11-05         2024-12-08          31745.0             2.0
3      2022-03-13         2025-10-02          39674.0             1.0
4      2024-04-05         2024-12-15              NaN             8.0
...           ...                ...              ...             ...
10195  2020-12-08         2025-01-25          24167.0             9.0
10196  2023-12-31         2025-05-07          11639.0             7.0
10197  2022-02-15         2025-01-11          43832.0             2.0
10198  2021-03-16         2025-05-14          18827.0            10.0
10199  2020-10-12         2025-06-27          35211.0            10.0

                          Email  Phone_Number Country
0      peckvictoria@example.com    2131107701   India
1      owensanthony@example.com    1080761560   india
2            tara39@example.org    8981006345   India
3        berrynancy@example.org    8228064204   india
4          denise84@example.org    2665569480   India
...                         ...           ...     ...
10195    barrycrane@example.net    5004696571   InDia
10196    lisadennis@example.net    5200349941     IND
10197       kelli74@example.org    8147428496   India
10198        dawn84@example.org    2987564247   InDia
10199  kochjonathan@example.org    1926206725   India

[10200 rows x 12 columns]

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   str
 1   Name                10200 non-null  str
 2   Gender              9174 non-null   str
 3   Age                 9249 non-null   str
 4   City                9184 non-null   str
 5   Signup_Date         10200 non-null  str
 6   Last_Purchase_Date  9188 non-null   str
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  str
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   str
dtypes: float64(2), int64(1), str(9)
memory usage: 956.4 KB

In [8]:
df.describe().round(2)

       Purchase_Amount  Feedback_Score  Phone_Number
count          9179.00         9177.00  1.020000e+04
mean          29090.13            5.48  4.979974e+09
std          208697.09            2.87  2.902593e+09
min            -500.00            1.00  9.208990e+05
25%           12295.00            3.00  2.449157e+09
50%           24330.00            5.00  4.988639e+09
75%           37130.00            8.00  7.510448e+09
max         9999999.00           10.00  9.994402e+09

In [15]:
df.isnull().sum()/len(df)*100

Customer_ID           10.029412
Name                   0.000000
Gender                10.058824
Age                    9.323529
City                   9.960784
Signup_Date            0.000000
Last_Purchase_Date     9.921569
Purchase_Amount       10.009804
Feedback_Score        10.029412
Email                  0.000000
Phone_Number           0.000000
Country                7.176471
dtype: float64

In [10]:
df.shape

(10200, 12)

In [16]:
df.dropna().shape

(4528, 12)

In [17]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [18]:
df['Customer_ID'].value_counts().head(10)

Customer_ID
CUST6560     2
CUST7652     2
CUST6833     2
CUST6106     2
CUST8964     2
CUST10852    2
CUST10824    2
CUST5403     2
CUST8461     2
CUST4196     2
Name: count, dtype: int64

In [20]:
df[df['Customer_ID'] == 'CUST6560']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
96,CUST6560,Jeremy Wallace,NaN,NaN,DELHI,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN
3517,CUST6560,Jeremy Wallace,NaN,NaN,Delhi,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN

In [22]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(f"{col}: {df[col].unique()}")
        print("")

Gender: <StringArray>
['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female', nan]
Length: 9, dtype: str
--------------------------------------------------
City: <StringArray>
[  ' KOLKATA ',           nan, ' hyderabad ',   ' CHENNAI ',   ' kolkata ',
 ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ',    ' Mumbai ',   ' chennai ',
     ' Delhi ', ' bangalore ',    ' MUMBAI ', ' Bangalore ',   ' Kolkata ',
     ' delhi ',   ' Chennai ',    ' mumbai ',     ' DELHI ']
Length: 19, dtype: str
--------------------------------------------------
Feedback_Score: [ 1.  2.  8. 10.  3.  9. nan  4.  7.  5.  6.]
--------------------------------------------------
Country: <StringArray>
['India', 'india', nan, 'InDia', 'IND']
Length: 5, dtype: str
--------------------------------------------------